services:
    bitbag_sylius_przelewy24_plugin.http_client:
        class: GuzzleHttp\Client
        public: false

    bitbag_sylius_przelewy24_plugin.bridge.przelewy24:
        class: BitBag\SyliusPrzelewy24Plugin\Bridge\Przelewy24Bridge
        public: true
        arguments:
            - "@bitbag_sylius_przelewy24_plugin.http_client"
